apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: kube-kadm-ui
  #annotations:
  #  metallb.universe.tf/loadBalancerIPs: 192.168.1.100
spec:
  selector:
    app: kube-kadm-ui
  ports:
    - name: ssh
      port: 22101
      targetPort: 22
      protocol: TCP
    - name: vnc
      port: 59000
      targetPort: 5900
      protocol: TCP
    - name: novnc
      port: 60800
      targetPort: 6080
      protocol: TCP
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: kube-kadm-ui
spec:
  selector:
    matchLabels:
      app: kube-kadm-ui # has to match .spec.template.metadata.labels
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: kube-kadm-ui # has to match .spec.selector.matchLabels
    spec:
      serviceAccountName: kube-kadm
      containers:
        - name: kube-kadm-ui
          image: quay.io/flysangel/image:app.kadm-v1.0.0
          imagePullPolicy: Always
          command:
            - '/bin/bash'
            - '-c'
            - 'sudo /usr/sbin/sshd -D'
          # run podman
          securityContext:
            privileged: true
          ports:
              # ssh
            - hostPort: 22101
              containerPort: 22
              protocol: TCP
              # kubevirt
            - hostPort: 5900
              containerPort: 5900
              protocol: TCP
            - hostPort: 6080
              containerPort: 6080
              protocol: TCP
          env:
            - name: WINDOWS_W
              value: "1400"
            - name: WINDOWS_H
              value: "900"
            - name: VNC_PASSWD
              value: "vnc520"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: "1Gi"
      restartPolicy: Always
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - effect: NoSchedule
          operator: Exists
