apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    spec:
      containers:
      - name: postgres
        image: postgres:11.2
        resources:
          requests:
            memory: "512Mi"
            cpu: "512m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
