apiVersion: v1
kind: ConfigMap
metadata:
  name: mail-config
data:
  # Use this to specify the domains to be served
  mail_domains: "tk8s.k8s"
  # Other custom configurations can go here
  postfix-main.cf: |
    mydomain = tk8s.k8s
    myhostname = mx1.tk8s.k8s
    mynetworks = 127.0.0.0/8 192.168.188.0/24 172.22.0.0/16
    mydestination = mx1.tk8s.k8s, tk8s.k8s
    # smtpd_relay_restrictions = permit_mynetworks
