# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.9.3
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-10-02T07:30:16Z"
  labels:
    app: pmbind
  name: pmbind
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    image: localhost/alp.bind:latest
    name: mbind
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /etc/bind/named.conf
      name: opt-zfs-pod-bind-k8s.mnamed.conf-host-0
    - mountPath: /etc/bind/zone
      name: opt-zfs-pod-bind-zone-host-1
  dnsConfig:
    searches:
    - k8s
  volumes:
  - hostPath:
      path: /opt/taroko/pod/bind/k8s.mnamed.conf
      type: File
    name: opt-zfs-pod-bind-k8s.mnamed.conf-host-0
  - hostPath:
      path: /opt/taroko/pod/bind/zone
      type: Directory
    name: opt-zfs-pod-bind-zone-host-1
