kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ${STU}   
  name:  ${STU}-clusterole
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["nodes", "persistentvolumes","secrets"]
  verbs: ["create",  "delete", "deletecollection", "get", "list", "patch", "update", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses", "volumeattachments", "csinodes", "csidrivers"]
  verbs: ["*"]

# https://kubernetes.io/docs/reference/kubectl/#resource-types

