kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ${STU}   
  name:  ${STU}-role
rules:
- apiGroups: ["*"]  
  resources: ["*","persistentvolumes", "persistentvolumeclaims"]
  verbs: ["*"]
