apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: echoserver
  name: echoserver
spec:
  containers:
  - image: registry.k8s.io/echoserver:1.10
    name: echoserver
    ports:
    - containerPort: 8080
      hostPort:  9000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
