apiVersion: v1
kind: Pod
metadata:
  name: gmm
  labels:
    app: gmm
spec:
  containers:
    - name: guacamole
      image: quay.io/flysangel/guacamole/guacamole:1.5.5
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
      env:
        - name: GUACD_HOSTNAME
          value: gmm
        - name: MYSQL_HOSTNAME
          value: gmm
        - name: MYSQL_DATABASE
          value: guacamole
        - name: MYSQL_USER
          value: guacamole
        - name: MYSQL_PASSWORD
          value: mymariadbguacamole
        - name: TZ
          value: Asia/Taipei
        # guacamole.properties
        # https://guacamole.apache.org/doc/gug/configuring-guacamole.html#standard-configuration-options-guacamole-properties
        - name: ALLOWED_LANGUAGES
          value: en
        # https://guacamole.apache.org/doc/gug/guacamole-docker.html#required-environment-variables
        - name: REMOTE_IP_VALVE_ENABLED
          value: "true"
        # https://guacamole.apache.org/doc/gug/recording-playback.html#installing-enabling-the-recording-storage-extension
        - name: RECORDING_ENABLED
          value: "true"
        # https://guacamole.apache.org/doc/gug/auth-ban.html#installing-enabling-brute-force-authentication-detection
        - name: BAN_ENABLED
          value: "true"
        # https://guacamole.apache.org/doc/gug/totp-auth.html
        - name: TOTP_ENABLED
          value: "false"
        # https://guacamole.apache.org/doc/gug/ldap-auth.html
        # ldap test ok
        #- name: LDAP_ENABLED
        #  value: "true"
        #- name: LDAP_HOSTNAME
        #  value: 172.20.1.181
        #- name: LDAP_PORT
        #  value: "389"
        #- name: LDAP_ENCRYPTION_METHOD
        #  value: none
        #- name: LDAP_USER_BASE_DN
        #  value: OU=DCUSER,DC=flymks,DC=com
        #- name: LDAP_USERNAME_ATTRIBUTE
        #  value: sAMAccountName
        #- name: LDAP_SEARCH_BIND_DN
        #  value: CN=guacamoleSearch,OU=DCUSER,DC=flymks,DC=com
        #- name: LDAP_SEARCH_BIND_PASSWORD
        #  value: "Aa123456789"
        #- name: LDAP_USER_SEARCH_FILTER
        #  value: "(memberOf=CN=guacamoleUser,OU=DCUSER,DC=flymks,DC=com)"
        # Custom login
        - name: LOGO
          value: prometheus
      volumeMounts:
        - name: recordings
          mountPath: /var/lib/guacamole/recordings

    - name: guacd
      image: quay.io/flysangel/guacamole/guacd:1.5.5
      imagePullPolicy: IfNotPresent
      env:
        - name: GUACD_LOG_LEVEL
          value: debug
      volumeMounts:
        - name: recordings
          mountPath: /var/lib/guacamole/recordings

    - name: mariadb
      image: quay.io/flysangel/gmm:mariadb-v1.0.6
      imagePullPolicy: IfNotPresent
      args:
        [
          "--character-set-server=utf8mb4",
          "--collation-server=utf8mb4_general_ci",
        ]
      env:
        - name: MARIADB_ROOT_PASSWORD
          value: root
        - name: MARIADB_DATABASE
          value: guacamole
        - name: MARIADB_USER
          value: guacamole
        - name: MARIADB_PASSWORD
          value: mymariadbguacamole
        - name: TZ
          value: Asia/Taipei
      volumeMounts:
        - name: mariadb
          mountPath: /var/lib/mysql

  volumes:
    - name: mariadb
      hostPath:
        path: ./gcm/mdb
    - name: recordings
      hostPath:
        path: ./gcm/gcm

  restartPolicy: Always

