apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: m1
  name: m1
spec:
  containers:
  - image: quay.io/cloudwalker/oracle.mysql
    name: m1
    volumeMounts:
    - mountPath: "/var/lib/mysql"
      name: mysql
  volumes:
  - name: mysql
    hostPath:
      path: /opt/mysql
