apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: quay.io/cloudwalker/alp.base
    command: ['sh', '-c', 'echo The Pod is running && sleep 10']
  restartPolicy: Never
