apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    kube-vip.io/loadbalancerIPs: "${VIPNET}.101"
spec:
  externalTrafficPolicy: Local
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
