apiVersion: v1
kind: Pod
metadata:
  name: pod-hostnk
spec:
#  hostNetwork: true
  containers:
  - name: fbs
    image: quay.io/cloudwalker/alp.fbs:24.1
    ports:
     - hostPort: 8080
       containerPort: 4000
  nodeName: c31-worker2
