apiVersion: v1
kind: Pod
metadata:
  labels:
    app: m1
  name: pod-mysql-hp
spec:
  runtimeClassName: crun
  containers:
  - image: quay.io/cloudwalker/oracle.mysql
    name: m1
    volumeMounts:
      - mountPath: "/var/lib/mysql"
        name: mysql
  volumes:
    - name: mysql
      hostPath:
        path: /opt/zfs/mysql
