apiVersion: v1
kind: Pod
metadata:
  name: pod-log
spec:
  containers:
  - name: pod-log
    image: quay.io/cloudwalker/alp.base
    command: ["/bin/sh"]
    args:
    - -c
    - |
      mkdir -p /var/log;i=0;
      while true;
      do
        echo "$(date) INFO $i";  
        i=$((i+1));
      done
