apiVersion: v1
kind: Pod
metadata:
  name: pod-crun
spec:
  runtimeClassName: crun
  containers:
  - name: base
    image: ghcr.io/tarokolabs/wulin/toolbox:v2026.8.0
    securityContext:
      privileged: true
