apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-storage
  annotations:
    volumeType: hostPath     # volumeType: <local or hostPath>
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Mi
