apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
data:
  password: U3Ryb25nUGFzc3dvcmQ=
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mdb
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-mdb
  labels:
    app: mariadb  
spec:
  containers:
  - name: mariadb
    image: mariadb
    imagePullPolicy: "IfNotPresent"
    env:
    - name: MARIADB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mariadb-secret
          key: password
    - name: MARIADB_USER
      value: "wordpress"
    - name: MARIADB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mariadb-secret
          key: password
    ports:
    - containerPort: 3306
      name: mariadb
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mariadb-data
  volumes:
  - name: mariadb-data
    hostPath:
      path: /opt/zfs/mariadb
