apiVersion: v1
kind: Pod
metadata:
  name: pod-wp
  labels:
    app: wordpress
spec:
  containers:
  - image: wordpress
    imagePullPolicy: "IfNotPresent"
    name: wordpress
    env:
    - name: WORDPRESS_DB_HOST
      value: "svc-mdb.default"
    - name: WORDPRESS_DB_NAME
      value: "wordpress"
    - name: WORDPRESS_DB_USER
      value: "root"
    - name: WORDPRESS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mariadb-secret
          key: password
    ports:
    - containerPort: 80
      hostPort: 8080
    volumeMounts:
    - name: wordpress-pv
      mountPath: /var/www/html
  volumes:
  - name: wordpress-pv
    hostPath:
      path: /opt/taroko/wordpress
  nodeSelector:
    app: taroko
