apiVersion: v1
kind: Pod
metadata:
  labels:
    run: echoserver
  name: echoserver
spec:
  containers:
  - image: registry.k8s.io/echoserver:1.10
    name: echoserver
    resources: 
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  restartPolicy: Always
