apiVersion: v1
kind: Service
metadata:
  name: svc-promgo
  labels:
    app: promgo
spec:
  #type: NodePort
  #externalTrafficPolicy: Local
  selector:
    app: promgo
  ports:
  - port: 8888
    targetPort: 8888
