apiVersion: v1
kind: Service
metadata:
  name: svc-prom
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9090'
    kube-vip.io/loadbalancerIPs: "172.22.64.109"
spec:
  selector:
    app: prometheus-server
  externalTrafficPolicy: Local
  ports:
    - port: 9090
      targetPort: 9090 
      nodePort: 30090
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
