apiVersion: v1
kind: Service
metadata:
  name: mt-svc
  namespace: taroko
  annotations:
    kube-vip.io/loadbalancerIPs: "172.22.64.102" 
spec:
  externalTrafficPolicy: Local
  selector:
    app: mt
  ports:
    - protocol: TCP
      port: 22100
      targetPort: 22100
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
