apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: pvc-mysql
spec:
  storageClassName: sc-mysql
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 10Gi
