apiVersion: v1
kind: ServiceAccount
metadata:
  name: xtkadm
  namespace: taroko
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xtkadm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: xtkadm
  namespace: taroko
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xtkadm
  name: xtkadm
  namespace: taroko
spec:
  ports:
  - port: 3389
    protocol: TCP
    targetPort: 3389
    nodePort: 30089
  selector:
    app: xtkadm
  type: NodePort
  externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xtkadm
  name: xtkadm
  namespace: taroko
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xtkadm
  template:
    metadata:
      labels:
        app: xtkadm
    spec:
      containers:
      - image: quay.io/flysangel/rdp:xfce4-v1.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
             fieldPath: status.hostIP
        name: xtkadm
        command:
        - /bin/bash
        - -c
        - |
          sudo rm -rf /run/dbus/pid /var/run/xrdp/xrdp-sesman.pid /var/run/xrdp/xrdp.pid
          sudo /usr/bin/dbus-daemon --system --fork
          sudo /usr/sbin/xrdp-sesman
          sudo /usr/sbin/xrdp
          sudo useradd -m -s /bin/bash rbean
          echo 'rbean:rbean' | sudo chpasswd
          sudo install -m 0755 -d /run/sshd
          sudo /usr/sbin/sshd -D -e
        ports:
        - containerPort: 22
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 1Gi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      hostname: xtkadm
      restartPolicy: Always
      serviceAccountName: xtkadm
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 2Gi
        name: dshm
