#spark.jars.packages org.apache.iceberg:iceberg-spark-runtime-3.4_2.12-1.7.1
spark.master                    yarn
spark.yarn.am.memory            512M
spark.executor.memory           1024m
spark.driver.memory             1024m
#spark.yarn.submit.waitAppCompletion true
#spark.eventLog.enabled          true
#spark.eventLog.dir              hdfs://dtm-0:8020/tmp/spark-events
#spark.history.fs.logDirectory   hdfs://dtm-0:8020/tmp/spark-events


spark.sql.extensions org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.demo org.apache.iceberg.spark.SparkCatalog
#spark.sql.catalog.demo.io-impl org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.demo.warehouse s3a://spark/demo/
spark.sql.catalog.demo.s3.endpoint https://minio.s3:9000
spark.sql.defaultCatalog demo
spark.sql.catalog.demo.type hadoop

spark.hadoop.fs.s3a.access.key minio
spark.hadoop.fs.s3a.secret.key minio123
spark.hadoop.fs.s3a.endpoint http://minio.s3:9000
spark.hadoop.fs.s3a.connection.ssl.enabled false
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.impl org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
