apiVersion: v1
kind: ServiceAccount
metadata:
  name: tkadm
  namespace: taroko
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tkadm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: tkadm
  namespace: taroko
---
apiVersion: v1
kind: Service
metadata:
  name: tkadm
  namespace: taroko
  annotations:
    tkport: "tkgw:22100:22100"
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: tkadm
  ports:
    - protocol: TCP
      port: 22100
      targetPort: 22100
      nodePort: 32200
---
apiVersion: v1
kind: Service
metadata:
  name: dkreg
  namespace: taroko
  annotations:
    tkport: "none:5000:5000"
spec:
  selector:
    app: tkadm
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tkadm 
  labels:
    app: tkadm
  namespace: taroko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tkadm
  template:
    metadata:
      labels:
        app: tkadm
      name: tkadm
      namespace: taroko
      annotations:
        kubectl.kubernetes.io/default-container: "tkadm"
    spec:
     dnsPolicy: None
     dnsConfig:
      nameservers:
      - 10.98.0.10
      searches:
      - svc.k1.k8s
      - taroko.svc.k1.k8s
      - svc-lkh.lkh.svc.k1.k8s
      - svc-dt.dt.svc.k1.k8s
      - svc-dip.dip.svc.k1.k8s
      options:
      - name: ndots
        value: "5"
     volumes:
     - name: dkreg-storage
       hostPath:
         path: /opt/zfs/dkreg
     - name: podman-storage
       hostPath:
         path: /opt/zfs/podman
     - name: wulin-storage
       hostPath:
         path: /opt/wulin
     - name: zfs-storage
       hostPath:
         path: /opt/zfs
     serviceAccountName: tkadm
     hostname: tkadm
     containers:
     - name: tkadm
       image: ghcr.io/tarokolabs/wulin/admin:v2026.8.0
#       imagePullPolicy: Always
       imagePullPolicy: IfNotPresent
       tty: true
       ports:
       - containerPort: 22100
       lifecycle:
         postStart:
           exec:
             command:
             - /bin/bash
             - -c
             - |
               cp -p /var/tmp/htpasswd /opt/dkreg
               n=$(echo $HOST_IP | cut -d'.' -f3,4)
               hip=$(echo $n | tr '.' '_')
               hostname "tkadm_${hip}"
       securityContext:
         privileged: true
#         no-new-privileges: false
#         allowPrivilegeEscalation: true
       volumeMounts:
       - name: dkreg-storage
         mountPath: /opt/dkreg
       - name: podman-storage
         mountPath: /var/lib/containers/storage
       - name: wulin-storage
         mountPath: /home/bigred/wulin
       - name: zfs-storage
         mountPath: /opt/zfs
       env:
       - name: KUBERNETES_SERVICE_HOST
         value: "kubernetes.default"
       - name: KUBERNETES_SERVICE_PORT_HTTPS
         value: "443"
       - name: KUBERNETES_SERVICE_PORT
         value: "443"
       - name: REGISTRY_STORAGE_DELETE_ENABLED
         value: "true"
       - name: HOST_IP
         valueFrom:
           fieldRef:
             fieldPath: status.hostIP
       securityContext:
         privileged: true
     - image: ghcr.io/distribution/distribution:3.1.1
       imagePullPolicy: IfNotPresent
       name: dkreg
       ports:
       - containerPort: 5000
#         hostPort: 5000
       volumeMounts:
       - mountPath: "/var/lib/registry"
         name: dkreg-storage
       env:
       - name: REGISTRY_AUTH
         value: "htpasswd"
       - name: REGISTRY_AUTH_HTPASSWD_PATH
         value: "/var/lib/registry/htpasswd"
       - name: REGISTRY_AUTH_HTPASSWD_REALM
         value: "Registry Realm"
       - name: REGISTRY_STORAGE_DELETE_ENABLED
         value: "true"    
 #    nodeSelector:
 #      app: taroko
