apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 確保 namespace 存在
namespace: monitoring

resources:
  - alertmanager-config.yaml
  - alertmanager-deployment.yaml
  - alertmanager-service.yaml
