apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: pvc-n8n
  name: pvc-n8n
  namespace: n8n
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
