ARG VER=0.0
ARG BASE_TAG=v2026.8.0
FROM ghcr.io/tarokolabs/wulin/toolbox:${BASE_TAG}
RUN apk update && apk upgrade && apk add bind tcpdump && \
    # 必需執行以下命令, 才可成功執行 sudo rndc dumpdb -cache 這命令
    rndc-confgen -a && chown -R root:root /etc/bind/ && \
    echo "/usr/sbin/named" > /usr/bin/ash.rc && \
    touch /etc/bind/named.conf
CMD ["/bin/ash"]
