options {
  directory "/etc/bind";
  pid-file "/var/run/named/named.pid";
  forwarders { 8.8.8.8; 168.95.1.1; };
  allow-query { any; };
  allow-recursion { any; };
  listen-on { any; };
  recursion yes;
};

zone "k8s" IN {
  type master;
  file "/etc/bind/zone/k8s.zone";
}; 

zone "tkca.k8s" IN {
  type master;
  file "/etc/bind/zone/tkca.k8s.zone";
};

zone "tkuk.k8s" IN {
  type master;
  file "/etc/bind/zone/tkuk.k8s.zone";
};
