apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kube-system
  name: pvc-kadm
spec:
  storageClassName: sc-kadm
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 10Gi
