apiVersion: v1
kind: Pod
metadata:
  name: nginx-crun
spec:
  runtimeClassName: crun
  containers:
  - name: nginx
    image: docker.io/library/nginx
  nodeSelector:
    kubernetes.io/hostname : c31-control-plane
