apiVersion: v1
kind: ServiceAccount
metadata:
  name: dipadm
  namespace: dip
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dipadm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: dipadm
  namespace: dip
---
apiVersion: v1
kind: Service
metadata:
  name: dipadm
  namespace: dip
#  annotations:
#    tkport: "tkgw:22102:22102"
spec:
  selector:
    dep: dipadm
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dipadm
  labels:
    dep: dipadm
  namespace: dip
spec:
  replicas: 1
  selector:
    matchLabels:
      dep: dipadm
  template:
    metadata:
      labels:
        dep: dipadm
      name: dipadm
      namespace: dip
    spec:
     dnsPolicy: None
     dnsConfig:
      nameservers:
      - 10.98.16.10
      searches:
      - svc-dip.dip.svc.tkdip.k8s
      - dip.svc.tkdip.k8s
      - svc.tkdip.k8s
     hostname: dipadm
     volumes:
     - name: wulin
       hostPath:
        path: /opt/wulin/
     - name: zfs-storage
       hostPath:
         path: /opt/zfs
     serviceAccountName: dipadm
     imagePullSecrets:
     - name: dkreg
#     runtimeClassName: crun
     containers:
     - name: dipadm
       image: dkreg.taroko:5000/usdt.hdp341
       imagePullPolicy: Always
       tty: true
       securityContext:
         privileged: true
       volumeMounts:
       - name: zfs-storage
         mountPath: /opt/zfs
       - name: wulin
         mountPath: /home/bigred/wulin
       ports:
       - containerPort: 22
         protocol: TCP
         hostPort: 22102
     nodeSelector:
       app: taroko
