apiVersion: v1
kind: Service
metadata:
  name: dipjupy
  namespace: dip
  labels:
    app: dipjupy
spec:
  clusterIP: None
  selector:
    app: dipjupy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-dipjupy
  labels:
    app: dipjupy
  namespace: dip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dipjupy
  template:
    metadata:
      labels:
        app: dipjupy
      name: dipjupy
      namespace: dip
    spec:
     dnsPolicy: None
     dnsConfig:
      nameservers:
      - 10.98.16.10
      searches:
      - svc-dip.dip.svc.tkdip.k8s
      - dip.svc.tkdip.k8s
      - svc.tkdip.k8s
     hostname: dipjupy
     volumes:
     - name: wulin
       hostPath:
        path: /opt/taroko/wulin/
     - name: zfs-storage
       hostPath:
         path: /opt/taroko
     imagePullSecrets:
     - name: dkreg
     containers:
     - name: dipjupy
       image: dkreg.taroko:5000/us.jupyter
       imagePullPolicy: Always
       tty: true
       command: ["/bin/bash", "-c"]
       args:
         - |
           source /opt/taroko/sys/usdt.bash
           # mkdir -p /home/bigred/hdfs
           # sudo mount -t nfs -o vers=3,proto=tcp,nolock,noacl,sync 172.22.8.3:/  /home/bigred/hdfs
           jupyter lab --allow-root --ip=0.0.0.0 --no-browser \
           --ServerApp.terminado_settings="shell_command=['/bin/bash']" \
           --FileContentsManager.delete_to_trash=False 
       securityContext:
         privileged: true
       volumeMounts:
       - name: zfs-storage
         mountPath: /opt/taroko
       - name: wulin
         mountPath: /home/bigred/wulin
       ports:
       - containerPort: 8888
         protocol: TCP
         hostPort: 8888
     nodeSelector:
       app: taroko
