apiVersion: v1
kind: Secret
metadata:
  namespace: psql
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: bigred
  POSTGRES_PASSWORD: bigred
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: bigboss
  POSTGRES_NON_ROOT_PASSWORD: bigboss
