apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  annotations:
    kube-vip.io/loadbalancerIPs: "172.22.64.188" 
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
