spark.master                    yarn
spark.yarn.am.memory            512M
spark.executor.memory           1024m
spark.driver.memory             1024m
spark.yarn.submit.waitAppCompletion false

#Turns on logging for applications submitted from this machine
spark.eventLog.enabled          true
spark.eventLog.dir              hdfs://dtm-0:8020/tmp/spark-events
spark.history.fs.logDirectory   hdfs://dtm-0:8020/tmp/spark-events

#spark.sql.extensions   org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
#spark.executor.heartbeatInterval 300000
#spark.network.timeout 400000

# iceberg catalog
#spark.sql.catalog.iceberg    org.apache.iceberg.spark.SparkCatalog
#spark.sql.catalog.iceberg.type   hadoop
#spark.sql.catalog.iceberg.warehouse   iceberg-warehouse

# demo catalog
#spark.sql.catalog.demo org.apache.iceberg.spark.SparkCatalog
#spark.sql.catalog.demo.io-impl org.apache.iceberg.aws.s3.S3FileIO
#spark.sql.catalog.demo.warehouse s3a://demo/
#spark.sql.catalog.demo.s3.endpoint https://minio.s3:9000
#spark.sql.catalog.demo.type hadoop  
