apiVersion: v1
kind: Service
metadata:
  name: svc-grafana
  namespace: grafana
spec:
  selector:
    app: dep-grafana
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 3000
      targetPort: 3000 
      nodePort: 30030
