apiVersion: v1
kind: Service
metadata:
  name: dthba
  namespace: dt
  annotations:
    tkport: "tkgw:16010:16010"
spec:
  selector:
    statefulset.kubernetes.io/pod-name: dtw-2
  ports:
   - name: hbase
     port: 16010
     protocol: TCP
     targetPort: 16010
