apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-iperf
spec:
#  selector:
#    matchLabels:
#      app: iperf3
  template:
    spec:
      runtimeClassName: gvisor
      containers:
      - name: iperf3
        image: quay.io/cloudwalker/alp.base
        command: ["iperf3"]
        args: ["-s", "-p 12345"]
        ports:
        - containerPort: 12345
          hostPort: 12345
