FROM ubuntu:24.04

COPY bash.append /tmp/
RUN  mkdir -p /etc/skel/.ssh /opt/taroko/www /opt/taroko/dataset /opt/taroko/sys
COPY ssh/* /etc/skel/.ssh/
COPY environment /etc/

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y nano locales apt-utils tree unzip curl wget jq libsnappy-dev \
    ncat net-tools ssh zip sudo iputils-ping dnsutils libssl-dev openjdk-17-jdk libisal-dev gettext-base \
    python3 python3-pip psmisc iproute2 mysql-client bsdmainutils && \
    apt-get -y upgrade && apt-get autoremove -y && apt-get clean && rm -rf /var/cache/apt/archives && \

    locale-gen en_US && locale-gen zh_TW.UTF-8 && locale-gen en_US.UTF-8 && passwd -dl root && \
    ln -sf /usr/share/zoneinfo/Asia/Taipei /etc/localtime && \

    pip3 install --break-system-packages numpy pandas pyarrow fastparquet mysql-connector-python && \

    # install kubectl
    curl -LO https://dl.k8s.io/release/v1.35.5/bin/linux/amd64/kubectl && \
    chmod +x kubectl && mv kubectl /usr/local/bin && \

    # 建立管理者帳號 bigred
    groupadd bigboss && echo '%bigboss ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers && \
    cat /tmp/bash.append >> /etc/bash.bashrc && rm /tmp/bash.append && chmod 755 /etc/bash.bashrc && \
    useradd -m -s /bin/bash bigred && echo 'bigred:bigred' | chpasswd && \
    usermod -a -G bigboss bigred && chmod -R 700 /home/bigred/.ssh && \

    echo 'PubkeyAuthentication yes' >> /etc/ssh/sshd_config && \
    echo 'PermitUserEnvironment yes' >> /etc/ssh/sshd_config && \
    echo 'StrictHostKeyChecking no' >> /etc/ssh/ssh_config && \ 

    echo 'DefaultTasksMax=1024' >> /etc/systemd/system.conf && \
    rm /etc/update-motd.d/* && echo "Data Technology Platform (Ubuntu 24.04 LTS)" >/etc/update-motd.d/00 && \
    chmod +x /etc/update-motd.d/00 && cat /etc/update-motd.d/00 > /etc/motd 

CMD ["/bin/bash"]
