ARG VER=0.0
FROM ghcr.io/tarokolabs/tk8s/toolbox:v2026.8.0
COPY crictl.yaml /etc/crictl.yaml 
RUN apk update && apk upgrade && apk add --no-cache containerd containerd-ctr cri-tools 

CMD ["/usr/bin/containerd"]
    
