ARG VER=0.0
ARG BASE_TAG=v2026.8.0
FROM ghcr.io/tarokolabs/wulin/toolbox:${BASE_TAG}
COPY crictl.yaml /etc/crictl.yaml 
RUN apk update && apk upgrade && apk add --no-cache containerd containerd-ctr cri-tools 

CMD ["/usr/bin/containerd"]
    
