apiVersion: v1
kind: Service
metadata:
  name: lkhhs2
  namespace: lkh
  annotations:
    tkport: "tkgw:10000:10000"
  labels:
    app: lkhhs2
spec:
  ports:
   - name: hs2
     port: 10000
     protocol: TCP
     targetPort: 10000
   - name: ssh
     port: 22
     protocol: TCP
     targetPort: 22
  selector:
    app: lkhhs2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-lkhhs2
  labels:
    app: lkhhs2
  namespace: lkh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lkhhs2
  template:
    metadata:
      labels:
        app: lkhhs2
      name: lkhhs2
      namespace: lkh
    spec:
     dnsPolicy: None
     dnsConfig:
      nameservers:
      - 10.98.64.10
      searches:
      - svc-lkh.lkh.svc.tklkh.k8s
      - lkh.svc.tklkh.k8s
      - svc.tklkh.k8s
     hostname: lkhhs2
     volumes:
     - name: wulin
       hostPath:
        path: /opt/wulin/
     - name: zfs-storage
       hostPath:
         path: /opt/zfs
     - name: db
       hostPath:
        path: /opt/zfs/db
     imagePullSecrets:
     - name: dkreg
     # runtimeClassName: crun
     containers:
     - name: lkhhs2
       image: dkreg.taroko:5000/uslkh
       imagePullPolicy: IfNotPresent
       command: ["/opt/zfs/sys/hs2/start.sh"]
       # tty: true
       securityContext:
         privileged: true
       volumeMounts:
       - name: zfs-storage
         mountPath: /opt/zfs
       - name: wulin
         mountPath: /home/bigred/wulin
       ports:
       - containerPort: 10000
         protocol: TCP
         hostPort: 10000
     - name: metadb
       image: dkreg.taroko:5000/oracle.mysql8.0
       imagePullPolicy: IfNotPresent
       tty: true
       securityContext:
         privileged: true
       volumeMounts:
       - name: zfs-storage
         mountPath: /opt/zfs
       - name: db
         mountPath: /var/lib/mysql
       ports:
       - containerPort: 3306
     nodeSelector:
       app: taroko
