apiVersion: v1
kind: Service
metadata:
  name: mysql84
  namespace: lkh
  labels:
    app: mysql84
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql84
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-mysql84
  labels:
    app: mysql84
  namespace: lkh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql84
  template:
    metadata:
      labels:
        app: mysql84
      name: mysql84
      namespace: lkh
    spec:
     dnsPolicy: None
     dnsConfig:
      nameservers:
      - 10.98.64.10
      searches:
      - svc-lkh.lkh.svc.tklkh.k8s
      - svc.tklkh.k8s
      - lkh.svc.tklkh.k8s
     hostname: mysql84
     volumes:
     - name: db
       hostPath:
        path: /opt/zfs/mysql84
     - name: zfs-storage
       hostPath:
         path: /opt/zfs
     imagePullSecrets:
     - name: dkreg
     containers:
     - name: mysql84
       image: dkreg.taroko:5000/oracle.mysql
       imagePullPolicy: IfNotPresent
       tty: true
       securityContext:
         privileged: true
       volumeMounts:
       - name: zfs-storage
         mountPath: /opt/zfs
       - name: db
         mountPath: /var/lib/mysql
       ports:
       - containerPort: 3306
#     nodeSelector:
#       app: taroko
